#! /usr/bin/bash
# ==============================================================================================
# BSD 3-Clause Clear License
# Copyright © 2025 ZAMA. All rights reserved.
# ----------------------------------------------------------------------------------------------
# This script modifies the script <my_module>_run.tcl generated by EDAlize after the config phase
# input :
# <my_module>_run.tcl <my_module>_checkpoint_impl.dcp
# Modify the <my_module>_run.tcl script to support OOC
# Add checkpoint generation
# ----------------------------------------------------------------------------------------------
# Parse input
# ==============================================================================================

run_file=$1
checkpoint_file=$2
shift
shift

# Modify <my_module>_run.tcl
# When ooc, do not ask launch_runs impl_1 to do step write bitstream (indeed there is no bistream)
sed -e 's/launch_runs impl_1 -to_step write_bitstream/\
  set mode_ooc [expr {[string compare [get_property {STEPS.SYNTH_DESIGN.ARGS.MORE OPTIONS}  [get_runs synth_1] -quiet] "-mode out_of_context"]==0}]\n\
  if {$mode_ooc} {\
    puts "In OOC mode : no bitstream generation."\
    launch_runs impl_1\
  } else {\
    launch_runs impl_1 -to_step write_bitstream\
  }/' -i $run_file

sed -e 's/file copy -force \(.*\)$/\
if {$mode_ooc} {} else {\
  file copy -force \1\
}/' -i $run_file

#echo "write_checkpoint -force $checkpoint_file" >> $run_file
