#! /usr/bin/bash
# ==============================================================================================
# BSD 3-Clause Clear License
# Copyright © 2025 ZAMA. All rights reserved.
# ----------------------------------------------------------------------------------------------
# This script modifies the script <my_module>.tcl generated by EDAlize after the config phase
# input :
# <my_module>.tcl <files to be appended>
#
# Append the list of files at the end of the first file : to set vivado properties for example.
# ----------------------------------------------------------------------------------------------
# Parse input
# ==============================================================================================

append_file=$1
shift

# Modify <my_module>.tcl
for i in "$@"; do
    cat $i >> $append_file
done

