#! /usr/bin/bash
# ==============================================================================================
# BSD 3-Clause Clear License
# Copyright © 2025 ZAMA. All rights reserved.
# ----------------------------------------------------------------------------------------------
# This script modifies the script <my_module>_synth.tcl generated by EDAlize after the config phase
# input :
# <my_module>_synth.tcl <my_module>_checkpoint_syn.dcp
#
# ----------------------------------------------------------------------------------------------
# Parse input
# ==============================================================================================

synth_file=$1
checkpoint_file=$2
shift
shift

#Modify the exit
sed -e 's/exit\(.*\)$/set error \1/' -i $synth_file

#echo "write_checkpoint -force $checkpoint_file" >> $synth_file
echo "exit[\$error]" >> $synth_file
