# ==============================================================================================
# BSD 3-Clause Clear License
# Copyright © 2025 ZAMA. All rights reserved.
# ==============================================================================================

# == Ethernet reference clock
# 322.265625 MHz GT reference clock for MRMAC (4x25GE)
create_clock -period 3.103 -name gt_ref_clk_p -waveform {0.000 1.552} [get_ports gt_ref_clk_p]

# == CDC constraints for clk_mhdma (390MHz, MMCM clk_out2)
# clk_mhdma is generated by mhdma_clk_wiz from clk_pl_1 (33MHz freerun).
# GT transceivers produce per-channel TXOUTCLK recovered clocks.
# These three clock domains are asynchronous to each other.
set qsfp_mmcm_pin [get_pins -hierarchical -filter {NAME =~ *hpu_plug_wrapper/hpu_plug_i/shell_wrapper/clock_reset/mhdma_clk_wiz/clk_out2*}]

# clk_pl_1 (MMCM input) -> clk_mhdma (MMCM output): reset and control paths
set_max_delay -datapath_only -from \
    [get_clocks clk_pl_1] -to \
    [get_clocks -of_objects $qsfp_mmcm_pin \
] 2.8

# GT TXOUTCLK <-> clk_mhdma: MRMAC TX datapath CDC
set_max_delay -datapath_only -from \
    [get_clocks -of_objects [get_pins -hierarchical -filter {NAME =~ */gt_quad_base*/inst/quad_inst/CH*_TXOUTCLK}]] -to \
    [get_clocks -of_objects $qsfp_mmcm_pin \
] 2.8

set_max_delay -datapath_only -from \
  [get_clocks -of_objects $qsfp_mmcm_pin] -to \
  [get_clocks -of_objects [get_pins -hierarchical -filter {NAME =~ */gt_quad_base*/inst/quad_inst/CH*_TXOUTCLK}] \
] 2.8

# == Ethernet GT placement
# Top right SL1, bank 111 - port 4. Meant for MRMAC_X0Y3, one clock region away from this transceiver
set_property LOC GTM_QUAD_X0Y9    [get_cells -hier -filter {name =~ */gt_quad_base*/inst/quad_inst}]
set_property LOC GTM_REFCLK_X0Y18 [get_cells -hier -filter {name =~ */util_ds_buf*/U0/USE_IBUFDS_GTME5.GEN_IBUFDS_GTME5[0].IBUFDS_GTME5_U}]
