module_name="hpu_regif_core_eth_2in3"
description="HPU ethernet configuration register interface. Will be accessed by RPU to define registers."
word_size_b = 32
offset = 0x50000
range = 0x10000
ext_pkg = ["axi_if_common_param_pkg", "axi_if_shell_axil_pkg"]

# =====================================================================================================================
[section.system]
description="system configuration"
offset= 0x0

[section.system.register.src_mac_addr]
  description="Source mac address: this Hpu mac address"
  owner="User"
  read_access="Read"
  write_access="Write"
  default={Cst=0x0}

[section.system.register.dst_mac_addr]
  description="Target mac address"
  owner="User"
  read_access="Read"
  write_access="Write"
  default={Cst=0x0}

[section.system.register.line]
  description="Different parameters for qsfp lines"
  owner="User"
  read_access="Read"
  write_access="Write"
  field.select    = {size_b=2, offset_b=0,  default={Cst=0x0}, description="line selection"}
  field.loopback  = {size_b=3, offset_b=2,  default={Cst=0x0}, description="line loopback configurations"}
  field.rate      = {size_b=8, offset_b=5,  default={Cst=0x0}, description="line rates"}
  field.debug     = {size_b=1, offset_b=31, default={Cst=0x0}, description="States wherether we are in debug mode"}

[section.system.register.dummy_val3]
  description="Place-holder"
  owner="Parameter"
  read_access="Read"
  write_access="None"
  default={Cst=0x35353535}

# =====================================================================================================================
[section.reset]
offset= 0x14
description="different resets are available"

[section.reset.register.datapath]
  description="programmable datapath resets"
  owner="User"
  read_access="Read"
  write_access="Write"
  field.rx_rst={size_b=4, offset_b=8, default={Cst=0x0}, description="line selection"}
  field.tx_rst={size_b=4, offset_b=4, default={Cst=0x0}, description="line selection"}
  field.gt_all={size_b=4, offset_b=0, default={Cst=0x0}, description="line loopback configurations"}

[section.reset.register.monitor]
  description="reset done monitoring"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  field.rst_done={size_b=8, offset_b=0, default={Cst=0x0}, description="rst done monitoring"}

# =====================================================================================================================
[section.line]
offset= 0x1000
description="Line parameter sections"

[section.line.register.debug]
  description="Different parameters for debugging qsfp lines"
  owner="User"
  read_access="Read"
  write_access="Write"
  field.rx_to_tx        = {size_b=1, offset_b=29, default={Cst=0x0}, description="a"}
  field.tx_loop         = {size_b=1, offset_b=30, default={Cst=0x0}, description="b"}
  field.reset_registers = {size_b=1, offset_b=31, default={Cst=0x0}, description="c"}

# =====================================================================================================================
[section.fifo_write]
offset= 0x101C
description="fifo write part"

[section.fifo_write.register.number_of_words]
  description="numbers of words in a frame"
  owner="User"
  read_access="Read"
  write_access="Write"
  default={Cst=0x0}

[section.fifo_write.register.words_to_write_a]
  description="word that must be sent to fifo"
  owner="User"
  read_access="Read"
  write_access="Write"
  default={Cst=0x0}

[section.fifo_write.register.words_to_write_b]
  description="word that must be sent to fifo"
  owner="User"
  read_access="Read"
  write_access="Write"
  default={Cst=0x0}

[section.fifo_write.register.fifo_write_data_count]
  description="numbers of words that have been written"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  default={Cst=0x0}

# =====================================================================================================================
[section.fifo_read]
offset= 0x102C
description="fifo write part"

[section.fifo_read.register.words_to_read_a]
  description="word that must be sent to fifo"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  default={Cst=0x0}

[section.fifo_read.register.words_to_read_b]
  description="word that must be sent to fifo"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  default={Cst=0x0}

[section.fifo_read.register.fifo_read_data_count]
  description="numbers of words that have been written"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  default={Cst=0x0}


# =====================================================================================================================
[section.cnt]
offset= 0x103C
description="fifo write part"

[section.cnt.register.trig_rd]
  description="trig_rd"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  default={Cst=0x0}

[section.cnt.register.tx_wr]
  description="tx_wr"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  default={Cst=0x0}

[section.cnt.register.words]
  description="words"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  default={Cst=0x0}

# =====================================================================================================================
[section.stat]
offset= 0x104C
description="fifo write part"

[section.stat.register.status]
  description="fifo status"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  default={Cst=0x0}

[section.stat.register.clk_a]
  description="clock counts"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  default={Cst=0x0}

[section.stat.register.clk_b]
  description="clock counts"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  default={Cst=0x0}

[section.stat.register.valid_words_a]
  description="clock counts"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  default={Cst=0x0}

[section.stat.register.valid_words_b]
  description="clock counts"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  default={Cst=0x0}

[section.stat.register.sop_cnt_a]
  description="clock counts"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  default={Cst=0x0}

[section.stat.register.sop_cnt_b]
  description="clock counts"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  default={Cst=0x0}
