module_name="hpu_regif_core_eth_2in3"
description="HPU ethernet configuration register interface. Will be accessed by RPU to define registers."
word_size_b = 32
offset = 0x50000
range = 0x10000
ext_pkg = ["axi_if_common_param_pkg", "axi_if_shell_axil_pkg"]

# =====================================================================================================================
[section.mhdma_system]
description="system configuration"
offset= 0x0

[section.mhdma_system.register.lane]
  description="Different parameters for qsfp lines"
  owner="User"
  read_access="Read"
  write_access="Write"
  field.select    = {size_b=2, offset_b=0,  default={Cst=0x0}, description="line selection"}
  field.loopback  = {size_b=3, offset_b=2,  default={Cst=0x0}, description="line loopback configurations"}
  field.rate      = {size_b=8, offset_b=5,  default={Cst=0x0}, description="line rates"}
  field.debug     = {size_b=1, offset_b=31, default={Cst=0x0}, description="States whether we are in debug mode"}

[section.mhdma_system.register.timeout_notify]
  description="Timeout: time before re-launching a request, in clock cycles"
  owner="User"
  read_access="Read"
  write_access="Write"
  field.notify_timeout_dur  = {size_b=32, offset_b=0,  default={Cst=0x48000000}, description="notify request timeout duration"}

[section.mhdma_system.register.timeout_read_req]
  description="Timeout: time before re-launching a request, in clock cycles"
  owner="User"
  read_access="Read"
  write_access="Write"
  field.read_req_timout_dur = {size_b=32, offset_b=0, default={Cst=0x48000000}, description="read request timeout duration"}

[section.mhdma_system.register.fsm_value]
  description="fsm status of the module"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  default={Cst=0x0}

# =====================================================================================================================
[section.mhdma_reset]
offset= 0x14
description="Controllable resets for transceivers"

[section.mhdma_reset.register.datapath]
  description="GTM datapath resets"
  owner="User"
  read_access="Read"
  write_access="Write"
  field.rx_rst={size_b=4, offset_b=8, default={Cst=0x0}, description="resets on rx lane"}
  field.tx_rst={size_b=4, offset_b=4, default={Cst=0x0}, description="resets on tx lane"}
  field.gt_all={size_b=4, offset_b=0, default={Cst=0x0}, description="reset controlling both rx and tx at the same time"}

[section.mhdma_reset.register.monitor]
  description="Reset done flag for monitoring"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  field.rst_done={size_b=8, offset_b=0, default={Cst=0x0}, description="rst done monitoring"}

# =====================================================================================================================
[section.mhdma_hpu_id]
description="HPU ID containing all possible targets. For all IDs we have HPU MAC address, software ID and a flag for current hpu"
offset= 0x50

[section.mhdma_hpu_id.register.zero]
  description="HPU ID zero"
  owner="User"
  read_access="Read"
  write_access="Write"
  default={Cst=0x0}

[section.mhdma_hpu_id.register.one]
  description="HPU ID one"
  owner="User"
  read_access="Read"
  write_access="Write"
  default={Cst=0x0}

[section.mhdma_hpu_id.register.two]
  description="HPU ID two"
  owner="User"
  read_access="Read"
  write_access="Write"
  default={Cst=0x0}

[section.mhdma_hpu_id.register.three]
  description="HPU ID three"
  owner="User"
  read_access="Read"
  write_access="Write"
  default={Cst=0x0}

[section.mhdma_hpu_id.register.four]
  description="HPU ID four"
  owner="User"
  read_access="Read"
  write_access="Write"
  default={Cst=0x0}

[section.mhdma_hpu_id.register.five]
  description="HPU ID five"
  owner="User"
  read_access="Read"
  write_access="Write"
  default={Cst=0x0}

[section.mhdma_hpu_id.register.six]
  description="HPU ID six"
  owner="User"
  read_access="Read"
  write_access="Write"
  default={Cst=0x0}

[section.mhdma_hpu_id.register.seven]
  description="HPU ID seven"
  owner="User"
  read_access="Read"
  write_access="Write"
  default={Cst=0x0}

# =====================================================================================================================
[section.mhdma_request]
description="Request registers interface"
offset= 0x100

[section.mhdma_request.register.req_id]
  description="Different parameters for qsfp lines"
  owner="User"
  read_access="Read"
  write_access="WriteNotify"
  field.size_b  = {size_b=16, offset_b=0,  default={Cst=0x4000}, description="size request in bytes, default is ct size"}
  field.node_id = {size_b=4,  offset_b=16, default={Cst=0x0},    description="node id or HPU target id"}
  field.req_id  = {size_b=4,  offset_b=20, default={Cst=0x0},    description="request identifier"}
  field.iop_id  = {size_b=8,  offset_b=24, default={Cst=0x0},    description="IOP id from software point of view"}

[section.mhdma_request.register.req_addr]
  description="request address"
  owner="User"
  read_access="Read"
  write_access="WriteNotify"
  field.src = {size_b=16, offset_b=0,  default={Cst=0x0}, description="ciphertext source address"}
  field.dst = {size_b=16, offset_b=16, default={Cst=0x0}, description="ciphertext destination address"}

[section.mhdma_request.register.notify]
  description="When a notify is received, this register will be updated"
  owner="Kernel"
  read_access="ReadNotify"
  write_access="None"
  field.iop_id    = {size_b=4,  offset_b=0,  default={Cst=0x0}, description="what is the IOP ID of received Notify"}
  field.node_id   = {size_b=4,  offset_b=4,  default={Cst=0x0}, description="what HPU is the source of this Notify"}
  field.src_addr  = {size_b=16, offset_b=16, default={Cst=0x0}, description="what is the source address of the ct notified"}

[section.mhdma_request.register.read_request]
  description="When a read request has bneen processed, this register will be updated"
  owner="Kernel"
  read_access="ReadNotify"
  write_access="None"
  field.iop_id    = {size_b=4,  offset_b=0,  default={Cst=0x0}, description="what is the IOP ID of received ct"}
  field.node_id   = {size_b=4,  offset_b=4,  default={Cst=0x0}, description="from what HPU has been retreived this ct"}
  field.dst_addr  = {size_b=16, offset_b=16, default={Cst=0x0}, description="where is the ct"}

[section.mhdma_request.register.stat_notify]
  description="requests statistics each counter is up to 40seconds"
  owner="Kernel"
  read_access="ReadNotify"
  write_access="None"
  field.cnt_read    = {size_b=16, offset_b=16, default={Cst=0x0}, description="number of notify that have been sent"}

[section.mhdma_request.register.stat_notify_ack]
  description="requests statistics each counter is up to 40seconds"
  owner="Kernel"
  read_access="ReadNotify"
  write_access="None"
  field.cnt_ack     = {size_b=16, offset_b=0,  default={Cst=0x0}, description="number of notify ack that have been received"}

[section.mhdma_request.register.stat_notify_timeout]
  description="requests statistics each counter is up to 40seconds"
  owner="Kernel"
  read_access="ReadNotify"
  write_access="None"
  field.cnt_timeout = {size_b=16, offset_b=16, default={Cst=0x0}, description="timeout counter on notify"}

[section.mhdma_request.register.stat_notify_timeout_retry]
  description="requests statistics each counter is up to 40seconds"
  owner="Kernel"
  read_access="ReadNotify"
  write_access="None"
  field.cnt_retry   = {size_b=16, offset_b=16, default={Cst=0x0}, description="counter of number of retries that have been done"}

# =====================================================================================================================
[section.mhdma_lane]
offset= 0x200
description="Line parameter sections"

[section.mhdma_lane.register.debug]
  description="Different parameters for debugging qsfp lines"
  owner="User"
  read_access="Read"
  write_access="Write"
  field.rx_to_tx        = {size_b=1, offset_b=29, default={Cst=0x0}, description="a"}
  field.tx_loop         = {size_b=1, offset_b=30, default={Cst=0x0}, description="b"}
  field.reset_registers = {size_b=1, offset_b=31, default={Cst=0x0}, description="c"}

# =====================================================================================================================
[section.mhdma_hbm_axi4_addr_2in3]
offset= 0x1000
description="HBM AXI4 connection address offset"

[section.mhdma_hbm_axi4_addr_2in3.register.ct]
  description="Address offset for each ciphertext HBM AXI4 connection"
  owner="User"
  read_access="Read"
  write_access="Write"
  duplicate=["_pc0_lsb", "_pc0_msb","_pc1_lsb", "_pc1_msb"]

# =====================================================================================================================
[section.fifo_write]
offset= 0x101C
description="fifo write part"

[section.fifo_write.register.number_of_words]
  description="numbers of words in a frame"
  owner="User"
  read_access="Read"
  write_access="Write"
  default={Cst=0x0}

[section.fifo_write.register.words_to_write_a]
  description="word that must be sent to fifo"
  owner="User"
  read_access="Read"
  write_access="Write"
  default={Cst=0x0}

[section.fifo_write.register.words_to_write_b]
  description="word that must be sent to fifo"
  owner="User"
  read_access="Read"
  write_access="Write"
  default={Cst=0x0}

[section.fifo_write.register.fifo_write_data_count]
  description="numbers of words that have been written"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  default={Cst=0x0}

# =====================================================================================================================
[section.fifo_read]
offset= 0x102C
description="fifo write part"

[section.fifo_read.register.words_to_read_a]
  description="word that must be sent to fifo"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  default={Cst=0x0}

[section.fifo_read.register.words_to_read_b]
  description="word that must be sent to fifo"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  default={Cst=0x0}

[section.fifo_read.register.fifo_read_data_count]
  description="numbers of words that have been written"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  default={Cst=0x0}


# =====================================================================================================================
[section.cnt]
offset= 0x103C
description="fifo write part"

[section.cnt.register.trig_rd]
  description="trig_rd"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  default={Cst=0x0}

[section.cnt.register.tx_wr]
  description="tx_wr"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  default={Cst=0x0}

[section.cnt.register.words]
  description="words"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  default={Cst=0x0}

# =====================================================================================================================
[section.mhdma_stat]
offset= 0x104C
description="fifo write part"

[section.mhdma_stat.register.status]
  description="fifo status"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  default={Cst=0x0}

[section.mhdma_stat.register.clk_a]
  description="clock counts lsb"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  default={Cst=0x0}

[section.mhdma_stat.register.clk_b]
  description="clock counts msb"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  default={Cst=0x0}

[section.mhdma_stat.register.valid_words_a]
  description="valid rx word counter lsb"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  default={Cst=0x0}

[section.mhdma_stat.register.valid_words_b]
  description="valid rx word counter msb"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  default={Cst=0x0}

[section.mhdma_stat.register.sop_cnt_a]
  description="clock counter between tx sop and rx sop lsb"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  default={Cst=0x0}

[section.mhdma_stat.register.sop_cnt_b]
  description="clock counter between tx sop and rx sop msb"
  owner="Kernel"
  read_access="Read"
  write_access="None"
  default={Cst=0x0}
